export const C = {
    
    SET_STATUS_BY_MAC:"statusByMac/SET_STATUS_BY_MAC",
    SET_STATUS_BY_MAC_FAILED:"statusByMac/SET_STATUS_BY_MAC_FAILED",
    SET_STATUS_SEARCH_START:"statusByMac/SET_STATUS_SEARCH_START",
    SET_STATUS_SEARCH_RESULT:"statusByMac/SET_STATUS_SEARCH_RESULT",
    SET_STATUS_FETCHING:"statusByMac/SET_STATUS_FETCHING",
    SET_STATUS_TOGGLE_BUTTON:"statusByMac/SET_STATUS_TOGGLE_BUTTON",

    SET_PING_BY_MAC:"pingByMac/SET_PING_BY_MAC",
    SET_PING_BY_MAC_FAILED:"pingByMac/SET_PING_BY_MAC_FAILED",
    SET_PING_REQUEST_START:"pingByMac/SET_PING_REQUEST_START",
    SET_PING_REQUEST_RESULT:"pingByMac/SET_PING_REQUEST_RESULT",
    SET_PING_FETCHING:"pingByMac/SET_PING_FETCHING",

    SET_DVBC_BY_MAC:"dvbcByMac/SET_DVBC_BY_MAC",
    SET_DVBC_BY_MAC_FAILED:"dvbcByMac/SET_DVBC_BY_MAC_FAILED",
    SET_DVBC_REQUEST_START:"dvbcByMac/SET_DVBC_REQUEST_START",
    SET_DVBC_REQUEST_RESULT:"dvbcByMac/SET_DVBC_REQUEST_RESULT",
    SET_DVBC_FETCHING:"dvbcByMac/SET_DVBC_FETCHING",

    SET_LANGUAGE:"dataUI/SET_LANGUAGE",
    SET_LANGUAGE_FETCHING:"dataUI/SET_LANGUAGE_FETCHING",

    SET_AUTH_LOGIN:"auth/SET_LOGIN",
    SET_AUTH_LOGOUT:"auth/SET_LOGOUT",
    SET_AUTH_CHECK:"auth/SET_AUTH_CHECK",
    SET_AUTH_LOGIN_FAILED:"auth/SET_LOGIN_FAILED",
    SET_AUTH_LOGOUT_FAILED:"auth/SET_LOGOUT_FAILED",
    SET_AUTH_CHECK_FAILED:"auth/SET_CHECK_AUTH_FAILED",
    SET_AUTH_FETCHING:"dataUI/SET_AUTH_FETCHING",

    SET_INITIALIZE_SUCCESS:"appInit/SET_INITIALIZE_SUCCESS",

    SET_USERS_LIST:"usersList/SET_USERS_LIST",
    SET_USERS_LIST_FAILED:"usersList/SET_USERS_LIST_FAILED",
    SET_USERS_LIST_REQUEST_START:"usersList/SET_USERS_LIST_REQUEST_START",
    SET_USERS_LIST_REQUEST_RESULT:"usersList/SET_USERS_LIST_REQUEST_RESULT",
    SET_USERS_LIST_FETCHING:"usersList/SET_USERS_LIST_FETCHING",

    
    SET_ADD_USER_FAILED:"usersList/SET_ADD_USER_FAILED",
    SET_ADD_USER_REQUEST_START:"usersList/SET_ADD_USER_REQUEST_START",
    SET_ADD_USER_REQUEST_RESULT:"usersList/SET_ADD_USER_REQUEST_RESULT",
    SET_ADD_USER_FETCHING:"usersList/SET_ADD_USER_FETCHING",

   
    SET_DEL_USER_FAILED:"usersList/SET_DEL_USER_FAILED",
    SET_DEL_USER_REQUEST_START:"usersList/SET_DEL_USER_REQUEST_START",
    SET_DEL_USER_REQUEST_RESULT:"usersList/SET_DEL_USER_REQUEST_RESULT",
    SET_DEL_USER_FETCHING:"usersList/SET_DEL_USER_FETCHING",

   
    SET_CHANGE_USER_FAILED:"usersList/SET_CHANGE_USER_FAILED",
    SET_CHANGE_USER_REQUEST_START:"usersList/SET_CHANGE_USER_REQUEST_START",
    SET_CHANGE_USER_REQUEST_RESULT:"usersList/SET_CHANGE_USER_REQUEST_RESULT",
    SET_CHANGE_USER_FETCHING:"usersList/SET_CHANGE_USER_FETCHING",

    SET_OPEN_DELETE_DIALOG:"usersList/SET_OPEN_DELETE_DIALOG",
    SET_CLOSE_DELETE_DIALOG:"usersList/SET_CLOSE_DELETE_DIALOG",

    SET_PROFILE:"profile/SET_PROFILE",
    SET_PROFILE_FETCHING:"profile/SET_PROFILE_FETCHING",
    SET_PROFILE_FAILED:"profile/SET_PROFILE_FAILED",
}