export const C = {
//Initialize App (checking authorized or not)

    SET_INITIALIZE_SUCCESS:"appInit/SET_INITIALIZE_SUCCESS",


// Dashboard -> Status
    SET_STATUS_BY_MAC:"status/SET_STATUS_BY_MAC",
    SET_STATUS_BY_MAC_FAILED:"status/SET_STATUS_BY_MAC_FAILED",
    SET_STATUS_SEARCH_START:"status/SET_STATUS_SEARCH_START",
    SET_STATUS_SEARCH_RESULT:"status/SET_STATUS_SEARCH_RESULT",
    SET_STATUS_FETCHING:"status/SET_STATUS_FETCHING",
    
    SET_STATUS_PING:"status/SET_STATUS_PING",
    SET_STATUS_PING_FAILED:"status/SET_STATUS_PING_FAILED",
    SET_STATUS_PING_SEARCH_RESULT:"status/SET_STATUS_PING_SEARCH_RESULT",
    SET_STATUS_PING_FETCHING:"status/SET_STATUS_PING_FETCHING",

    SET_STATUS_DVBC:"status/SET_STATUS_DVBC",
    SET_STATUS_DVBC_FAILED:"status/SET_STATUS_DVBC_FAILED",
    SET_STATUS_DVBC_SEARCH_RESULT:"status/SET_STATUS_DVBC_SEARCH_RESULT",
    SET_STATUS_DVBC_FETCHING:"status/SET_STATUS_DVBC_FETCHING",

 // Dashboard -> Ping

    SET_PING_BY_MAC:"ping/SET_PING_BY_MAC",
    SET_PING_BY_MAC_FAILED:"ping/SET_PING_BY_MAC_FAILED",
    SET_PING_REQUEST_START:"ping/SET_PING_REQUEST_START",
    SET_PING_REQUEST_RESULT:"ping/SET_PING_REQUEST_RESULT",
    SET_PING_FETCHING:"ping/SET_PING_FETCHING",


 // Dashboard -> DVB-C

    SET_DVBC_BY_MAC:"dvbc/SET_DVBC_BY_MAC",
    SET_DVBC_BY_MAC_FAILED:"dvbc/SET_DVBC_BY_MAC_FAILED",
    SET_DVBC_REQUEST_START:"dvbc/SET_DVBC_REQUEST_START",
    SET_DVBC_REQUEST_RESULT:"dvbc/SET_DVBC_REQUEST_RESULT",
    SET_DVBC_FETCHING:"dvbc/SET_DVBC_FETCHING",

 // Change Languages

    SET_LANGUAGE:"lang/SET_LANGUAGE",
    SET_LANGUAGE_FETCHING:"lang/SET_LANGUAGE_FETCHING",

// Authentification

    SET_AUTH_LOGIN:"auth/SET_LOGIN",
    SET_AUTH_LOGOUT:"auth/SET_LOGOUT",
    SET_AUTH_CHECK:"auth/SET_AUTH_CHECK",
    SET_AUTH_LOGIN_FAILED:"auth/SET_LOGIN_FAILED",
    SET_AUTH_LOGOUT_FAILED:"auth/SET_LOGOUT_FAILED",
    SET_AUTH_CHECK_FAILED:"auth/SET_CHECK_AUTH_FAILED",
    SET_AUTH_FETCHING:"auth/SET_AUTH_FETCHING",

// Users Page actions   

    SET_USERS_LIST:"users/SET_USERS_LIST",
    SET_USERS_LIST_FAILED:"users/SET_USERS_LIST_FAILED",
    SET_USERS_LIST_REQUEST_START:"users/SET_USERS_LIST_REQUEST_START",
    SET_USERS_LIST_REQUEST_RESULT:"users/SET_USERS_LIST_REQUEST_RESULT",
    SET_USERS_LIST_FETCHING:"users/SET_USERS_LIST_FETCHING",

    
    SET_ADD_USER_FAILED:"users/SET_ADD_USER_FAILED",
    SET_ADD_USER_REQUEST_START:"users/SET_ADD_USER_REQUEST_START",
    SET_ADD_USER_REQUEST_RESULT:"users/SET_ADD_USER_REQUEST_RESULT",
    SET_ADD_USER_FETCHING:"users/SET_ADD_USER_FETCHING",

   
    SET_DEL_USER_FAILED:"users/SET_DEL_USER_FAILED",
    SET_DEL_USER_REQUEST_START:"users/SET_DEL_USER_REQUEST_START",
    SET_DEL_USER_REQUEST_RESULT:"users/SET_DEL_USER_REQUEST_RESULT",
    SET_DEL_USER_FETCHING:"users/SET_DEL_USER_FETCHING",

   
    SET_CHANGE_USER_FAILED:"users/SET_CHANGE_USER_FAILED",
    SET_CHANGE_USER_REQUEST_START:"users/SET_CHANGE_USER_REQUEST_START",
    SET_CHANGE_USER_REQUEST_RESULT:"users/SET_CHANGE_USER_REQUEST_RESULT",
    SET_CHANGE_USER_FETCHING:"users/SET_CHANGE_USER_FETCHING",

    SET_OPEN_DELETE_DIALOG:"users/SET_OPEN_DELETE_DIALOG",
    SET_CLOSE_DELETE_DIALOG:"users/SET_CLOSE_DELETE_DIALOG",

// Profile actions

    SET_PROFILE:"profile/SET_PROFILE",
    SET_PROFILE_FETCHING:"profile/SET_PROFILE_FETCHING",
    SET_PROFILE_FAILED:"profile/SET_PROFILE_FAILED",
}